import { asArray, asRecord, numeric } from "../src/shared";
import type { Fingerprint, JournalEntry, ResourceKind } from "./journal";
import { close } from "./money";

const RANK: Record<ResourceKind, number> = {
  recurring: 0,
  payment: 1,
  expense: 2,
  group: 3,
};

/** Rules first, so they stop creating expenses, then payments and expenses, then groups. */
export function deletionOrder(entries: JournalEntry[]) {
  return entries
    .filter(
      (entry) =>
        entry.id !== null &&
        entry.status !== "absent" &&
        entry.status !== "ambiguous" &&
        entry.status !== "pending",
    )
    .sort((left, right) => RANK[left.kind] - RANK[right.kind]);
}

export function isInactive(body: unknown) {
  const row = asRecord(body);
  if (row.deletedAt != null || row.deleted_at != null) return true;
  if (row.deleted === true || row.isDeleted === true) return true;
  if (row.archived === true || row.isArchived === true) return true;
  const state = String(row.status ?? "").toLowerCase();
  return state === "deleted" || state === "inactive" || state === "archived";
}

/**
 * A candidate belongs to this run when the full marker is present and the
 * recorded fingerprint matches exactly. A shared prefix is not enough.
 */
export function matchesFingerprint(
  marker: string,
  fingerprint: Fingerprint,
  row: unknown,
) {
  if (marker.length < 8) return false;
  const record = asRecord(row);
  const title =
    typeof record.title === "string"
      ? record.title
      : typeof record.name === "string"
        ? record.name
        : undefined;
  const description =
    typeof record.description === "string" ? record.description : undefined;
  if (fingerprint.title !== undefined && title !== fingerprint.title) return false;
  if (
    fingerprint.description !== undefined &&
    description !== fingerprint.description
  ) {
    return false;
  }
  if (fingerprint.title === undefined && fingerprint.description === undefined) {
    return false;
  }
  const blob = `${title ?? ""}\n${description ?? ""}`;
  if (!blob.includes(marker)) return false;
  if (
    fingerprint.amount !== undefined &&
    !close(numeric(record.amount), fingerprint.amount)
  ) {
    return false;
  }
  if (
    fingerprint.groupId !== undefined &&
    (record.groupId ?? null) !== fingerprint.groupId
  ) {
    return false;
  }
  return true;
}

export function reconcileEntry(
  marker: string,
  entry: JournalEntry,
  rows: unknown[],
) {
  if (entry.status !== "pending" || entry.id) return entry.status;
  const found = rows.filter((row) =>
    matchesFingerprint(marker, entry.fingerprint, row),
  );
  if (found.length === 1) {
    const id = asRecord(found[0]).id;
    if (typeof id !== "string" || !id) return "ambiguous" as const;
    entry.id = id;
    entry.status = "active";
    return "active" as const;
  }
  if (found.length === 0) {
    // A definitive command answered, so the row is not coming. A timeout,
    // gateway error, or crash stays pending: the server can still commit.
    if (entry.responseSeen === true) {
      entry.status = "absent";
      return "absent" as const;
    }
    return "pending" as const;
  }
  entry.status = "ambiguous";
  return "ambiguous" as const;
}

/**
 * Known ids are deleted only when the row still carries this run's marker,
 * or when an expense was generated by a rule this journal recorded.
 */
export function ownsRow(
  marker: string,
  entry: JournalEntry,
  row: unknown,
  ruleIds: ReadonlySet<string>,
) {
  const record = asRecord(row);
  if (entry.id && record.id !== undefined && record.id !== entry.id) return false;
  const title = typeof record.title === "string" ? record.title : "";
  const name = typeof record.name === "string" ? record.name : "";
  const description =
    typeof record.description === "string" ? record.description : "";
  if (`${title}\n${name}\n${description}`.includes(marker)) return true;
  const ruleId = record.recurringExpenseRuleId ?? entry.ruleId;
  return (
    entry.kind === "expense" &&
    entry.source === "generated" &&
    typeof ruleId === "string" &&
    ruleIds.has(ruleId)
  );
}

/** Rows that contain this run's full marker. A shorter shared prefix does not qualify. */
export function markedRows(marker: string, rows: unknown[]) {
  if (marker.length < 8) return [];
  const found: Array<{
    id: string;
    title: string | null;
    description: string | null;
  }> = [];
  for (const row of rows) {
    const record = asRecord(row);
    const title =
      typeof record.title === "string"
        ? record.title
        : typeof record.name === "string"
          ? record.name
          : null;
    const description =
      typeof record.description === "string" ? record.description : null;
    if (!`${title ?? ""}\n${description ?? ""}`.includes(marker)) continue;
    if (typeof record.id !== "string" || !record.id) continue;
    found.push({ id: record.id, title, description });
  }
  return found;
}

export function idsIn(rows: unknown[]) {
  const ids = new Set<string>();
  for (const row of rows) {
    const id = asRecord(row).id;
    if (typeof id === "string" && id) ids.add(id);
  }
  return ids;
}

export function pageItems(body: unknown) {
  if (Array.isArray(body)) return body;
  return asArray(asRecord(body).items);
}
